language: java
deploy:
  provider: cloudfoundry
  username: $CF_USERNAME
  password: $CF_PASSWORD
  organization: $CF_ORG
  space: $CF_SPACE
  manifest: manifest.yml
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^pcfpuch_CI|master$